# Generated by Django 2.2.5 on 2020-09-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='check_in',
            field=models.IntegerField(),
        ),
    ]
